#!/bin/bash

# Find the 10 newest files in the current directory and store them in an array
files=($(ls -lt | grep -v '^d' | awk '{print $NF}' | head -n 10))

# Iterate over the array and print each file on a new line
for file in "${files[@]}"
do
    echo $file
done
